# NumPy Random Module

In [1]:
import numpy as np
from numpy import random as r

## Generate random numbers


* randint(low, <high=None>, <size=None>, <dtype=int>)  -  Generates random integers between low and high.
* rand(shape)  -  Generate random float values between 0 & 1 in the specifed shape. 
* using randint() which takes size as parameter, we can generate random array of desired shape and size.
* choice()    -    Takes array as parameter and returns one random value out of the array values. Can also take size as parameter and based on that it returns array of values.



In [2]:
#Generating random array of intergers from 0 to 25 of size = 20
intArray = r.randint(0,25,size=20)
print(intArray,"\n")

#Generating random array of float values of shape 3x2x3
floatArray = r.rand(3,2,3)
print(floatArray,"\n")

#Generating random array out of intArray f shape 4x3
choiceArray = r.choice(intArray,size=(4,3))
print(choiceArray,"\n")

[ 8 15 13  4 23 16  8  8 11 13  8 16  6 18 14  4  5  2  8 21] 

[[[0.40645318 0.34032863 0.84699263]
  [0.50021258 0.35130513 0.32219884]]

 [[0.27670197 0.13909366 0.2534512 ]
  [0.2910537  0.55434587 0.6466693 ]]

 [[0.9934135  0.12871262 0.61938645]
  [0.03972335 0.41667784 0.7265027 ]]] 

[[23 14 13]
 [11 11  8]
 [ 8 13  5]
 [11 16  8]] 



## Random Data Distribution

Generate a 2-D array containing 30 values of shape 5x6, where each value has to be 3, 5, 7 or 9.

* The probability for the value to be 3 is set to be 0.1

* The probability for the value to be 5 is set to be 0.3

* The probability for the value to be 7 is set to be 0.6

* The probability for the value to be 9 is set to be 0

In [3]:
#Probability priority order : 7 -> 5 -> 3 -> 9
#9 will never occur since it's probability of occurance is 0.
sampleArray = r.choice([3,5,7,9],p=[0.1,0.3,0.6,0],size=(5,6))
print(sampleArray)

[[7 7 5 7 7 5]
 [7 7 7 5 7 7]
 [7 7 3 7 7 7]
 [7 7 7 7 7 7]
 [7 5 5 3 7 7]]


## Random Permutation

Permutation - Arrangement of elements in different ways

* shuffle() : re-arranges the original array
* permutation() : returns the re-arranged array and leaves the original array un-touched

In [7]:
arr1 = np.array([1,3,4,6,2,8])

print(f'Original Array :\n{arr1}\n')

#permutation method
arr2 = r.permutation(arr1)

print(f'Original Array after permutation method is applied:\n{arr1}\n')
print(f'Array after permutation method is applied:\n{arr2}\n')

#shuffle method
r.shuffle(arr1)

print(f'Original Array after shuffle method is applied:\n{arr1}\n')

Original Array :
[1 3 4 6 2 8]

Original Array after permutation method is applied:
[1 3 4 6 2 8]

Array after permutation method is applied:
[8 3 1 6 4 2]

Original Array after shuffle method is applied:
[1 3 2 6 8 4]

