 * Creating ndarray with different dimensions


In [1]:
import numpy as np

#0D array
array1 = np.array(42)

#1D array
array2 = np.array([2,5,45,26])

#2D array
array3 = np.array([[1,2,3,4],[5,6,7,8]])

#3D array
array4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("0D array:",array1)
print("\n1D array:",array2)
print("\n2D array:",array3)
print("\n3D array:",array4)

0D array: 42

1D array: [ 2  5 45 26]

2D array: [[1 2 3 4]
 [5 6 7 8]]

3D array: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


* 'ndim' attribute is used to check the dimension of the ndarray 

In [2]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)

0
1
2
3


* To know the size of items store in the array we itemsize attribute.

In [3]:
print(array1.itemsize)

4


* To create an array with 0 filled in each place, we use zeros() method.

In [4]:
zeroArray = np.zeros((4,5)) #Inside the zeros() method, pass the shape of an array you want to create
onesArray = np.ones((3,5)) #Inside the ones() method, pass the shape of an array you want to create
print(zeroArray)
print("\n",onesArray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


* We use arange() function which give elements within that range
* We use linspace() function to get linearly spaced elements

In [5]:
arrayArange = np.arange(0,5) #arange(start,stop,step)
arrayLinspace = np.linspace(0,10,5) #linspace(start,stop,numberOfElements)

print("Arange array : ",arrayArange)
print("\nLinpsapce array : ",arrayLinspace)

Arange array :  [0 1 2 3 4]

Linpsapce array :  [ 0.   2.5  5.   7.5 10. ]


* Creating higher dimensional array using 'ndmin' attribute.

In [6]:
arr = np.array([1,2,3,4,5,6], ndmin=7)
print(f"Dimension of the array is : {arr.ndim}")
print(arr)

Dimension of the array is : 7
[[[[[[[1 2 3 4 5 6]]]]]]]


* Array Indexing to Access the elements

In [7]:
#Accessing 1D array
print(array2[3]) #Accessing 4th element in 1D array 'array2'

#Accessing 2D array
print(array3[1,2]) #Accessing 3rd element of 2nd array in 2D array 'array3'

#Accessing 3D array
print(array4[1,0,1]) #Accessing 2nd element of 1st array of 2nd array in 3D array 'array4'

#Accessing elements ny negative indexing
print(array2[-2]) #Accessing last 2nd element from array2
print(array3[0,-1]) #Accessing last element of 1st array from array3
print(array4[1,1,-1]) #Accessing last element of 2nd array of 2nd array


26
7
8
45
4
12


* Slicing

In [8]:
print(array2[0:3]) #Slicing array2 from index 0 till index 3(not included)
print(array3[1, 1:3]) #Slicing array3 from index 1 till index 3(not included) of 2nd array 
print(array3[0:2, 1]) #Getting 2nd element of both 1st and 2nd array from array3 
print(array4[0:,0:,1]) #Getting 2nd element of all the arrays of all dimension from array4. Returns 2D arraay

[ 2  5 45]
[6 7]
[2 6]
[[ 2  5]
 [ 8 11]]


* Data Types

In [9]:
arrint = np.array([1, 2, 3, 4])
arrstr = np.array(['apple', 'banana', 'cherry']) #Unicode string [U]
print(arrint.dtype)
print(arrstr.dtype)

int32
<U6


* Creating arrays with different data types

In [10]:
#Creating an ndarray of string data type
arraytype = np.array([1,2,3], dtype='S')

#Creating an ndarray of float data type of size 64
arraytype1 = np.array([3,4,8,5], dtype = np.float64)

print(arraytype.dtype)
print(arraytype1.dtype)

|S1
float64


* To know the size of an array i.e., the no. of elements in an array, we use size attribute.

In [11]:
print("Array size of arraytype : ",arraytype.size)
print("\nArray size of arraytype1 : ",arraytype1.size)

Array size of arraytype :  3

Array size of arraytype1 :  4


* Converting the data type of an array using 'astype()'

In [12]:
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([1.1, 2.1, 3.1])
arr3 = np.array([1, 0, 3])

newarr1 = arr1.astype('i') #Converting the float into integer by using 'i' as parameter
newarr2 = arr2.astype('S') #Converting the float into string 
newarr3 = arr3.astype(bool) #Converting the integer into boolean type

print(newarr1)
print(newarr1.dtype)
print(newarr2)
print(newarr2.dtype)
print(newarr3)
print(newarr3.dtype)

[1 2 3]
int32
[b'1.1' b'2.1' b'3.1']
|S32
[ True False  True]
bool


* NumPy copy() vs view()

copy() - owns the data and no connection between original and copy

view() - doesn't owns the data and any change in either of the array it'll affect the other

base - If it returns the base array, then that array does not owns the data.
       If it returns 'none', then that array owns the data.

In [13]:
arrayExample = np.array([1,2,3,4,5,6])

arrayView = arrayExample.view() #Creating view of an array
arrayCopy = arrayExample.copy() #Creating copy of an array

arrayView[1] = 8 #Changing the value in view array
arrayCopy[1] = 7 #Changing the value in copy array

print(f'After modifiying the view and copy arrays\nOriginal Array: {arrayExample}\nView Array: {arrayView}\nCopy Array: {arrayCopy}\n')

arrayExample[-1] = 9
print(f'After modifiying the original array\nOriginal Array: {arrayExample}\nView Array: {arrayView}\nCopy Array: {arrayCopy}\n')

#To check if the array owns the data or not
print(arrayView.base)
print(arrayCopy.base)

After modifiying the view and copy arrays
Original Array: [1 8 3 4 5 6]
View Array: [1 8 3 4 5 6]
Copy Array: [1 7 3 4 5 6]

After modifiying the original array
Original Array: [1 8 3 4 5 9]
View Array: [1 8 3 4 5 9]
Copy Array: [1 7 3 4 5 6]

[1 8 3 4 5 9]
None


* Shape of an array : Gives you the number of elements in each dimension  ('shape')

In [14]:
print(array1.shape) #0D array
print(array2.shape) #1D array
print(array3.shape) #2D array
print(array4.shape) #3D array

()
(4,)
(2, 4)
(2, 2, 3)


* Reshaping Array using 'reshape()' method





In [15]:
arrayForReshape = np.array([1,2,3,4,5,6,7,8])

#Changing 1D to 2D
array2D = arrayForReshape.reshape(4,2)
print("Reshaped array from 1D to 2D:\n",array2D)

#Changing 1D to 3D
array3D = arrayForReshape.reshape(2,2,2)
print("\nReshaped array from 1D to 3D:\n",array3D)

#When you don't store the reshaped array into new variable, then it returns as view of the original array
print("\n",arrayForReshape.reshape(2,4).base)

#Reshaping an array by passing one of the dimension as unkown by passing it as '-1'
arrayUnknown = arrayForReshape.reshape(4,2,-1)
print(f"\nReshapped array by passing one of the dimension as unknown: \n{arrayUnknown}\nAnd the dimension after reshaping is : \n{arrayUnknown.shape}")

#Flattening an array
arrayFlattening = array3D.reshape(-1)
print("\nFlattening array3D:\n",arrayFlattening)

Reshaped array from 1D to 2D:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Reshaped array from 1D to 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

 [1 2 3 4 5 6 7 8]

Reshapped array by passing one of the dimension as unknown: 
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
And the dimension after reshaping is : 
(4, 2, 1)

Flattening array3D:
 [1 2 3 4 5 6 7 8]


* Iterating through arrays using nditer()

In [16]:
for scalar in np.nditer(array3D) :
    print(scalar)

1
2
3
4
5
6
7
8


* Iterating Array With Different Data Types

In [17]:
for scalar in np.nditer(arrayUnknown, op_dtypes = 'S', flags=['buffered']) :
    print(scalar)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'


In [18]:
for index, scalar in np.ndenumerate(array3D) :
    print(index, scalar)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


* Join arrays using concatenate()


In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arrayJoin = np.concatenate((arr1, arr2))

print(arrayJoin)

[1 2 3 4 5 6]


* Join two 2-D arrays along rows (axis=1):

In [20]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[5,6,7],[7,8,9]])

#Joining the array along the rows by passing axis = 1.
arrJoinWithAxis = np.concatenate((arr3,arr4), axis=1)

#Joining the array along the rows without axis
arrJoinWithoutAxis = np.concatenate((arr3,arr4))

print(f'Join with axis :\n{arrJoinWithAxis}\n\nJoin without axis:\n{arrJoinWithoutAxis}')

Join with axis :
[[1 2 3 5 6 7]
 [4 5 6 7 8 9]]

Join without axis:
[[1 2 3]
 [4 5 6]
 [5 6 7]
 [7 8 9]]


* Stacking the arrays using stack()

In [21]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arrayStackWithAxis = np.stack((arr1, arr2),axis=1)
arrayStackWithoutAxis = np.stack((arr1, arr2))

print(f'Join with axis :\n{arrayStackWithAxis}\n\nJoin without axis:\n{arrayStackWithoutAxis}')

Join with axis :
[[1 4]
 [2 5]
 [3 6]]

Join without axis:
[[1 2 3]
 [4 5 6]]


* hstack() : to stack along rows
* vstack() : to stack along columns
* dstack() : to stack along depth or height

In [22]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arrayRowStack = np.hstack((arr1,arr2))
arrayColumnStack = np.vstack((arr1,arr2))
arrayDepthStack = np.dstack((arr1,arr2))

print(f'Stacking along ROWS:\n{arrayRowStack}\n\nStacking along COLUMNS:\n{arrayColumnStack}\n\nStacking along the DEPTH:\n{arrayDepthStack}')

Stacking along ROWS:
[1 2 3 4 5 6]

Stacking along COLUMNS:
[[1 2 3]
 [4 5 6]]

Stacking along the DEPTH:
[[[1 4]
  [2 5]
  [3 6]]]


* NumPy Splitting Array

In [23]:
arraySplit = np.array_split(arrayRowStack,3)

print(arraySplit)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
arraySplit1 = np.array_split(arr1, 2)

#When the elements is less than required
print(arraySplit1)

[array([1, 2]), array([3])]


In [25]:
print(arraySplit1[1])

[3]


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


* NumPy Array Searching using where()

In [69]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

#If yoou pass the below command, it will give you the first apperance of the specified element
#x = np.where(arr == 4)[0][0]
#[0][1]   -  Second appearance
#[0][n]   -  nth appearance

print(x)

(array([3, 5, 6], dtype=int64),)


* Finding the index values of even numbers in an array

In [28]:
arr = np.array([1,2,5,3,4,6,8,15,26,28,10,50])

evenNumberIndex = np.where(arr%2 == 0)
oddNumberIndex = np.where(arr%2 != 0) # or np.where(arr%2 ==1)

print(f'Even Number\'s Index values : {evenNumberIndex}\nOdd Number\'s Index values : {oddNumberIndex}')

Even Number's Index values : (array([ 1,  4,  5,  6,  8,  9, 10, 11], dtype=int64),)
Odd Number's Index values : (array([0, 2, 3, 7], dtype=int64),)


* Seach Sorted using searchsorted() : Which gives the index position where the specifed value would be inserted to maintain the search order

In [29]:
arr = np.array([0,1,2,3,5,7,9])

indexValue = np.searchsorted(arr, 4)

print(indexValue)

4


In [30]:
indexValueFromRight = np.searchsorted(arr, 4, side='right')

print(indexValueFromRight)

4


In [31]:
indexForMultipleVlaues = np.searchsorted(arr, [4,6,8])

print(indexForMultipleVlaues)

[4 5 6]


* Sorting an array using sort()

In [32]:
randomArray = np.array([5,9,3,4,8,0,2])

sortedArray = np.sort(randomArray)

print(f'Sorted array : {sortedArray}')

Sorted array : [0 2 3 4 5 8 9]


In [33]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [34]:

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


Filtering Arrays : 

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

In [35]:
arr = np.array([51,25,17,54,20,90])

indexValues = [True, True, False, True, False, False]

newArray = arr[indexValues]

print(f'Filtered array is : {newArray}')

Filtered array is : [51 25 54]


* The above one is hard coded. Now we filter using condition based approach for the above array itself


In [36]:
# this code will return the values which are below 50

#Creating an empty list to store the TRUE or FALSE values
indexValue1 = []

#To iter through the array
for value in np.nditer(arr):
    
    if value<50 :
        indexValue1.append(True)
        
    else :
        indexValue1.append(False)
        
print(f'Index where the values are below 20:\n{indexValue1}\n')

newArray1 = arr[indexValue1]

print(f'The values which are below 20 are : \n{newArray1}')

Index where the values are below 20:
[False, True, True, False, True, False]

The values which are below 20 are : 
[25 17 20]


* Creating Filter Directly From Array


In [42]:
#Below code returns the values which >=50

filterArrayIndex = arr >= 50

filterArray = arr[filterArrayIndex]

print(filterArray)

[51 54 90]


* Replace the elements in arr whose value is > 50 with 100

In [48]:
arr[arr>50] = 100
print(arr)

[100  25  17 100  20 100]


* min() : gives the minimum value of entire array
* max() : gives the maximum value of entire array
* sum() : gives the addition value of entire array
* sqrt() : gives the square root each element of entire array
* std() : gives the standard deviation of entire array

In [40]:
arrayExample = np.array([[1,4],[9,16],[25,36]])

print("Minimum value : ",arrayExample.min())
print("Maximum value : ",arrayExample.max())
print("Sum : ",arrayExample.sum()) #Sum of entire array
print("Sum along rows: ",arrayExample.sum(axis=1)) #By passign axis as 0 means it is column
print("Sum along columns : ",arrayExample.sum(axis=0)) #By passing axis as 1 means it is rows
print("Square root : \n",np.sqrt(arrayExample))
print("Standar Deviation : ",np.std(arrayExample))

Minimum value :  1
Maximum value :  36
Sum :  91
Sum along rows:  [ 5 25 61]
Sum along columns :  [35 56]
Square root : 
 [[1. 2.]
 [3. 4.]
 [5. 6.]]
Standar Deviation :  12.212243401148248


In [49]:
print("Original array:\n",arrayExample)

print("\nItems in C order:\n")
for item in np.nditer(arrayExample, order='C'): #C order - iter through rows
    print(item)
    
print("\nItems in F order:\n")
for item in np.nditer(arrayExample, order='F'): #F order - iter through column
    print(item)
    

Original array:
 [[ 1  4]
 [ 9 16]
 [25 36]]

Items in C order:

1
4
9
16
25
36

Items in F order:

1
9
25
4
16
36


In [52]:
print(arrayExample[::2,:]) #From start take every other row and all elements from selected array

[[ 1  4]
 [25 36]]


In [71]:
x = "Hello"[0]
print(x)


H
